name: Update Najaf Jobs

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Update jobs
        run: python update_jobs.py

      - name: Save updated jobs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add jobs.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update Najaf jobs"
            git push
          fi
